version: "3"
services:
  locator:
    image: apachegeode/geode
    hostname: locator
    deploy:
      resources:
        limits:
          memory: 800M
    expose:
      - "10334"
      - "1099"
      - "7575"
    ports:
      - "1099:1099"
      - "10334:10334"
      - "7575:7575"
      - "7070:7070"
    volumes:
      - ./scripts/:/scripts/
    command: /scripts/gfshWrapper.sh gfsh start locator --name=locator --mcast-port=0

  server:
    image: apachegeode/geode
    deploy:
      resources:
        limits:
          memory: 2G
    links:
      - locator:locator
    expose:
      - "8080"
      - "40404"
      - "1099"
    ports:
      - "40404"
    depends_on:
      - locator
    volumes:
      - ./scripts/:/scripts/
    command: /scripts/startServer.sh --server-port=40404 --max-heap=1G
